// Quiz answer key (encoded) — do not edit manually
// Generated by tools/encode-quiz-answers.js
const _qk = "UQhJRV9YWU8bCBBRCFBCCBBxGQYbBhsGGAYbdwYIT0QIEHEZBhsGGwYYBht3VwYISUVfWFlPGAgQUQhQQggQcRsGGAYbBhsGG3cGCE9ECBBxGwYYBhsGGwYbd1cGCElFX1hZTxkIEFEIUEIIEHEbBhsGGwYYBht3BghPRAgQcRsGGwYbBhgGG3dXBghJRV9YWU8eCBBRCFBCCBBxGwYbBhsGGwYbdwYIT0QIEHEbBhsGGwYbBht3VwYISUVfWFlPHwgQUQhQQggQcRsGGwYbBhgGG3cGCE9ECBBxGwYbBhsGGAYbd1cGCElFX1hZTxwIEFEIUEIIEHEYBhsGGwYaBhgGGwYZBhsGGwYbdwYIT0QIEHEYBhsGGwYaBhgGGwYZBhsGGwYbd1cGCElFX1hZTx0IEFEIUEIIEHEbBhgGGAYbBhsGGwYbBhsGGAYbdwYIT0QIEHEbBhgGGAYbBhsGGwYbBhsGGAYbd1dX";
function _dqk() {
  const raw = atob(_qk);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i) ^ 42;
  return JSON.parse(new TextDecoder().decode(bytes));
}
