// Quiz answer key (encoded) — do not edit manually
// Generated by tools/encode-quiz-answers.js
const _qk = "UQhJRV9YWU8bCBBRCFBCCBBxdwYIT0QIEHF3VwYISUVfWFlPGAgQUQhQQggQcXcGCE9ECBBxd1cGCElFX1hZTxkIEFEIUEIIEHF3BghPRAgQcXdXBghJRV9YWU8eCBBRCFBCCBBxdwYIT0QIEHF3VwYISUVfWFlPHwgQUQhQQggQcXcGCE9ECBBxd1cGCElFX1hZTxwIEFEIUEIIEHF3BghPRAgQcXdXVw==";
function _dqk() {
  const raw = atob(_qk);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i) ^ 42;
  return JSON.parse(new TextDecoder().decode(bytes));
}
